// <auto-generated />
using System;
using CardPortfolio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CardPortfolio.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200522160303_addedname")]
    partial class addedname
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CardPortfolio.Models.AutoLoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AutoLoanCategory")
                        .HasColumnType("int");

                    b.Property<double?>("DownPaymentPercentage")
                        .HasColumnType("float");

                    b.Property<bool>("HasFees")
                        .HasColumnType("bit");

                    b.Property<double?>("HighApr")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<double?>("LowApr")
                        .HasColumnType("float");

                    b.Property<double?>("MaximumAmount")
                        .HasColumnType("float");

                    b.Property<int?>("MaximumTermInMonths")
                        .HasColumnType("int");

                    b.Property<double?>("MinimumAmount")
                        .HasColumnType("float");

                    b.Property<int?>("MinimumTermInMonths")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("OriginationFee")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("AutoLoans");
                });

            modelBuilder.Entity("CardPortfolio.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abstract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BlogPostCategory")
                        .HasColumnType("int");

                    b.Property<int>("BlogPostSubCategory")
                        .HasColumnType("int");

                    b.Property<string>("BodyText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("CardPortfolio.Models.CashBack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("CashBackAmount")
                        .HasColumnType("float");

                    b.Property<int>("CashBackCategory")
                        .HasColumnType("int");

                    b.Property<double?>("CashBackSpendLimit")
                        .HasColumnType("float");

                    b.Property<int>("CashBackType")
                        .HasColumnType("int");

                    b.Property<int?>("CreditCardId")
                        .HasColumnType("int");

                    b.Property<bool>("HasLimit")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreditCardId");

                    b.ToTable("CashBacks");
                });

            modelBuilder.Entity("CardPortfolio.Models.CertificateAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("AprIfAmountNotMet")
                        .HasColumnType("float");

                    b.Property<double?>("BalanceToAvoidFee")
                        .HasColumnType("float");

                    b.Property<bool>("HasMaximumAmountForApr")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMinimumAmountForApr")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMinimumToOpenAccount")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMonthlyFee")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<double>("InterestRate")
                        .HasColumnType("float");

                    b.Property<double?>("MaximumAmountForApr")
                        .HasColumnType("float");

                    b.Property<double?>("MinimumAmountForApr")
                        .HasColumnType("float");

                    b.Property<double?>("MinimumToOpenAccount")
                        .HasColumnType("float");

                    b.Property<double>("MonthlyFee")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TermInMonths")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CertificateAccounts");
                });

            modelBuilder.Entity("CardPortfolio.Models.CheckingAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("AprIfAmountNotMet")
                        .HasColumnType("float");

                    b.Property<double?>("BalanceToAvoidFee")
                        .HasColumnType("float");

                    b.Property<double?>("DirectDepositRequirementsForAPR")
                        .HasColumnType("float");

                    b.Property<double?>("DirectDepositToAvoidMonthlyFee")
                        .HasColumnType("float");

                    b.Property<bool>("HasDirectDepositRequirementForAPR")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMaximumAmountForApr")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMinimumAmountForApr")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMinimumToOpenAccount")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMonthlyFee")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<double>("InterestRate")
                        .HasColumnType("float");

                    b.Property<double?>("InterestRateIfDDRequirementsNotMet")
                        .HasColumnType("float");

                    b.Property<double?>("MaximumAmountForApr")
                        .HasColumnType("float");

                    b.Property<double?>("MinimumAmountForApr")
                        .HasColumnType("float");

                    b.Property<double?>("MinimumToOpenAccount")
                        .HasColumnType("float");

                    b.Property<double>("MonthlyFee")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CheckingAccounts");
                });

            modelBuilder.Entity("CardPortfolio.Models.CreditCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("AnnualFee")
                        .HasColumnType("float");

                    b.Property<int>("CardCategory")
                        .HasColumnType("int");

                    b.Property<int>("CardNetwork")
                        .HasColumnType("int");

                    b.Property<double?>("CashAdvanceFee")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ForeignTransactionFee")
                        .HasColumnType("float");

                    b.Property<bool>("HasCashBack")
                        .HasColumnType("bit");

                    b.Property<bool>("HasIntroBalanceTransferFee")
                        .HasColumnType("bit");

                    b.Property<bool>("HasIntroBalanceTransferOffer")
                        .HasColumnType("bit");

                    b.Property<bool>("HasIntroPurchaseOffer")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSignUpBonus")
                        .HasColumnType("bit");

                    b.Property<double?>("HighAPRBalanceTransfer")
                        .HasColumnType("float");

                    b.Property<double?>("HighAPRCashAdvance")
                        .HasColumnType("float");

                    b.Property<double?>("HighAPRPurchases")
                        .HasColumnType("float");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<double?>("IntroBalanceTransferFee")
                        .HasColumnType("float");

                    b.Property<double?>("IntroBalanceTransferLengthInMonths")
                        .HasColumnType("float");

                    b.Property<double?>("IntroBalanceTransferRate")
                        .HasColumnType("float");

                    b.Property<double?>("IntroPurchaseLengthInMonths")
                        .HasColumnType("float");

                    b.Property<double?>("IntroPurchaseRate")
                        .HasColumnType("float");

                    b.Property<bool>("IsFixedRate")
                        .HasColumnType("bit");

                    b.Property<double?>("LowAPRBalanceTransfer")
                        .HasColumnType("float");

                    b.Property<double?>("LowAPRCashAdvance")
                        .HasColumnType("float");

                    b.Property<double?>("LowAPRPurchases")
                        .HasColumnType("float");

                    b.Property<double?>("MaximumCreditLine")
                        .HasColumnType("float");

                    b.Property<double?>("MinimumCreditLine")
                        .HasColumnType("float");

                    b.Property<decimal?>("MinimumPaymentInDollars")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("MinimumPaymentPercent")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<double?>("RegularBalanceTransferFee")
                        .HasColumnType("float");

                    b.Property<double?>("SignUpBonusAmount")
                        .HasColumnType("float");

                    b.Property<int>("SignUpBonusCategory")
                        .HasColumnType("int");

                    b.Property<double?>("SignUpBonusSpendRequirement")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.ToTable("CreditCards");
                });

            modelBuilder.Entity("CardPortfolio.Models.HomeEquityLineOfCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("AdvanceFee")
                        .HasColumnType("float");

                    b.Property<double?>("AnnualFee")
                        .HasColumnType("float");

                    b.Property<bool>("ArePaymentsInterestOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("HasAdvanceFee")
                        .HasColumnType("bit");

                    b.Property<bool>("HasAnnualFee")
                        .HasColumnType("bit");

                    b.Property<bool>("HasOriginationFee")
                        .HasColumnType("bit");

                    b.Property<double?>("HighApr")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<double?>("LTV")
                        .HasColumnType("float");

                    b.Property<double?>("LowApr")
                        .HasColumnType("float");

                    b.Property<double?>("MaximumAmount")
                        .HasColumnType("float");

                    b.Property<int?>("MaximumTermInMonths")
                        .HasColumnType("int");

                    b.Property<double?>("MinimumAmount")
                        .HasColumnType("float");

                    b.Property<double?>("MinimumPayment")
                        .HasColumnType("float");

                    b.Property<int?>("MinimumTermInMonths")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("OriginationFee")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("HomeEquityLinesOfCredit");
                });

            modelBuilder.Entity("CardPortfolio.Models.HomeEquityLoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("HasFees")
                        .HasColumnType("bit");

                    b.Property<double?>("HighApr")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<double?>("LTV")
                        .HasColumnType("float");

                    b.Property<double?>("LowApr")
                        .HasColumnType("float");

                    b.Property<double?>("MaximumAmount")
                        .HasColumnType("float");

                    b.Property<int?>("MaximumTermInMonths")
                        .HasColumnType("int");

                    b.Property<double?>("MinimumAmount")
                        .HasColumnType("float");

                    b.Property<int?>("MinimumTermInMonths")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("OriginationFee")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("HomeEquityLoans");
                });

            modelBuilder.Entity("CardPortfolio.Models.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AllowsBalanceTransferCash")
                        .HasColumnType("bit");

                    b.Property<int>("CreditBureau")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasRestrictionsToJoin")
                        .HasColumnType("bit");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstitutionType")
                        .HasColumnType("int");

                    b.Property<double?>("LengthBetweenCreditLineIncreases")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestrictionType")
                        .HasColumnType("int");

                    b.Property<double?>("ScoreForLowestAPR")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("CardPortfolio.Models.MoneyMarketAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("AprIfAmountNotMet")
                        .HasColumnType("float");

                    b.Property<double?>("BalanceToAvoidFee")
                        .HasColumnType("float");

                    b.Property<bool>("HasMaximumAmountForApr")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMinimumAmountForApr")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMinimumToOpenAccount")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMonthlyFee")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<double>("InterestRate")
                        .HasColumnType("float");

                    b.Property<double?>("MaximumAmountForApr")
                        .HasColumnType("float");

                    b.Property<double?>("MinimumAmountForApr")
                        .HasColumnType("float");

                    b.Property<double?>("MinimumToOpenAccount")
                        .HasColumnType("float");

                    b.Property<double>("MonthlyFee")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MoneyMarketAccounts");
                });

            modelBuilder.Entity("CardPortfolio.Models.Mortgage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("DownPaymentPercentage")
                        .HasColumnType("float");

                    b.Property<bool>("HasFees")
                        .HasColumnType("bit");

                    b.Property<double?>("HighApr")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<double?>("LoanToValue")
                        .HasColumnType("float");

                    b.Property<double?>("LowApr")
                        .HasColumnType("float");

                    b.Property<double?>("MaximumAmount")
                        .HasColumnType("float");

                    b.Property<int?>("MaximumTermInMonths")
                        .HasColumnType("int");

                    b.Property<double?>("MinimumAmount")
                        .HasColumnType("float");

                    b.Property<int?>("MinimumTermInMonths")
                        .HasColumnType("int");

                    b.Property<int>("MortgageType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("OriginationFee")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Mortgages");
                });

            modelBuilder.Entity("CardPortfolio.Models.SavingsAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("AprIfAmountNotMet")
                        .HasColumnType("float");

                    b.Property<double?>("BalanceToAvoidFee")
                        .HasColumnType("float");

                    b.Property<bool>("HasMaximumAmountForApr")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMinimumAmountForApr")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMinimumToOpenAccount")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMonthlyFee")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<double>("InterestRate")
                        .HasColumnType("float");

                    b.Property<double?>("MaximumAmountForApr")
                        .HasColumnType("float");

                    b.Property<double?>("MinimumAmountForApr")
                        .HasColumnType("float");

                    b.Property<double?>("MinimumToOpenAccount")
                        .HasColumnType("float");

                    b.Property<double>("MonthlyFee")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SavingsAccounts");
                });

            modelBuilder.Entity("CardPortfolio.Models.SecuredLineOfCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("AdvanceFee")
                        .HasColumnType("float");

                    b.Property<double?>("AnnualFee")
                        .HasColumnType("float");

                    b.Property<bool>("ArePaymentsInterestOnly")
                        .HasColumnType("bit");

                    b.Property<double?>("CollateralToLocRatio")
                        .HasColumnType("float");

                    b.Property<bool>("HasAdvanceFee")
                        .HasColumnType("bit");

                    b.Property<bool>("HasAnnualFee")
                        .HasColumnType("bit");

                    b.Property<bool>("HasOriginationFee")
                        .HasColumnType("bit");

                    b.Property<double?>("HighApr")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<double?>("LowApr")
                        .HasColumnType("float");

                    b.Property<double?>("MaximumAmount")
                        .HasColumnType("float");

                    b.Property<int?>("MaximumTermInMonths")
                        .HasColumnType("int");

                    b.Property<double?>("MinimumAmount")
                        .HasColumnType("float");

                    b.Property<double?>("MinimumPayment")
                        .HasColumnType("float");

                    b.Property<int?>("MinimumTermInMonths")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("OriginationFee")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("SecuredLinesOfCredit");
                });

            modelBuilder.Entity("CardPortfolio.Models.SecuredPersonalLoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("CollateralToLoanRatio")
                        .HasColumnType("float");

                    b.Property<bool>("HasFees")
                        .HasColumnType("bit");

                    b.Property<double?>("HighApr")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<double?>("LowApr")
                        .HasColumnType("float");

                    b.Property<double?>("MaximumAmount")
                        .HasColumnType("float");

                    b.Property<int?>("MaximumTermInMonths")
                        .HasColumnType("int");

                    b.Property<double?>("MinimumAmount")
                        .HasColumnType("float");

                    b.Property<int?>("MinimumTermInMonths")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("OriginationFee")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("SecuredPersonalLoans");
                });

            modelBuilder.Entity("CardPortfolio.Models.UnsecuredLineOfCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("AdvanceFee")
                        .HasColumnType("float");

                    b.Property<double?>("AnnualFee")
                        .HasColumnType("float");

                    b.Property<bool>("ArePaymentsInterestOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("HasAdvanceFee")
                        .HasColumnType("bit");

                    b.Property<bool>("HasAnnualFee")
                        .HasColumnType("bit");

                    b.Property<bool>("HasOriginationFee")
                        .HasColumnType("bit");

                    b.Property<double?>("HighApr")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<double?>("LowApr")
                        .HasColumnType("float");

                    b.Property<double?>("MaximumAmount")
                        .HasColumnType("float");

                    b.Property<int?>("MaximumTermInMonths")
                        .HasColumnType("int");

                    b.Property<double?>("MinimumAmount")
                        .HasColumnType("float");

                    b.Property<double?>("MinimumPayment")
                        .HasColumnType("float");

                    b.Property<int?>("MinimumTermInMonths")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("OriginationFee")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("UnsecuredLinesOfCredit");
                });

            modelBuilder.Entity("CardPortfolio.Models.UnsecuredPersonalLoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("HasFees")
                        .HasColumnType("bit");

                    b.Property<double?>("HighApr")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<double?>("LowApr")
                        .HasColumnType("float");

                    b.Property<double?>("MaximumAmount")
                        .HasColumnType("float");

                    b.Property<int?>("MaximumTermInMonths")
                        .HasColumnType("int");

                    b.Property<double?>("MinimumAmount")
                        .HasColumnType("float");

                    b.Property<int?>("MinimumTermInMonths")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("OriginationFee")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("UnsecuredPersonalLoans");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "2ad3ea48-9076-4434-972b-6576028c63cd",
                            ConcurrencyStamp = "b3512beb-34cf-4b0b-86b0-7835f09096a4",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("CardPortfolio.Models.CashBack", b =>
                {
                    b.HasOne("CardPortfolio.Models.CreditCard", null)
                        .WithMany("CashBack")
                        .HasForeignKey("CreditCardId");
                });

            modelBuilder.Entity("CardPortfolio.Models.CreditCard", b =>
                {
                    b.HasOne("CardPortfolio.Models.Institution", null)
                        .WithMany("CreditCards")
                        .HasForeignKey("InstitutionId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
